import { TProduto } from "@/core/produto/produto.entity";

export const MOCK_PRODUCTS: TProduto[] = [
  {
    id: "1",
    nome: "Água Mineral Crystal 500ml",
    descricao: "Água mineral natural sem gás",
    marca: "Crystal",
    categoria: "Água Mineral",
    precoCusto: 80,
    precoVenda: 150,
    precoRevenda: 120,
    precoPromocao: 130,
    quantidade: 100,
    estoqueMinimo: 20,
    ativo: true,
    promocao: false,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-12-10"),
  },
  {
    id: "2",
    nome: "Água Mineral Bonafont 1.5L",
    descricao: "Água mineral natural sem gás - garrafa família",
    marca: "Bonafont",
    categoria: "Água Mineral",
    precoCusto: 200,
    precoVenda: 350,
    precoRevenda: 280,
    precoPromocao: 300,
    quantidade: 50,
    estoqueMinimo: 10,
    ativo: true,
    promocao: true,
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-12-08"),
  },
  {
    id: "3",
    nome: "Água com Gás Perrier 330ml",
    descricao: "Água mineral com gás natural importada",
    marca: "Perrier",
    categoria: "Água com Gás",
    precoCusto: 400,
    precoVenda: 800,
    precoRevenda: 650,
    precoPromocao: null,
    quantidade: 25,
    estoqueMinimo: 5,
    ativo: true,
    promocao: false,
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-12-05"),
  },
  {
    id: "4",
    nome: "Água Saborizada Limão 500ml",
    descricao: "Água saborizada com limão natural",
    marca: "Fresh",
    categoria: "Água Saborizada",
    precoCusto: 120,
    precoVenda: 250,
    precoRevenda: 200,
    precoPromocao: null,
    quantidade: 0,
    estoqueMinimo: 15,
    ativo: false,
    promocao: false,
    createdAt: new Date("2024-04-05"),
    updatedAt: new Date("2024-12-01"),
  },
];

export const FILTER_OPTIONS = {
  CATEGORIES: [
    { value: "todos", label: "Todas as Categorias" },
    { value: "Água Mineral", label: "Água Mineral" },
    { value: "Água com Gás", label: "Água com Gás" },
    { value: "Água Saborizada", label: "Água Saborizada" },
  ],
  STATUS: [
    { value: "todos", label: "Todos os Status" },
    { value: "ativo", label: "Ativo" },
    { value: "inativo", label: "Inativo" },
    { value: "promocao", label: "Em Promoção" },
    { value: "estoque_baixo", label: "Estoque Baixo" },
  ],
};
